spring.application.name=ims

spring.datasource.url=jdbc:postgresql://dpg-d7n5tsvlk1mc7394n8jg-a.oregon-postgres.render.com:5432/ims_sjz6
spring.datasource.username=ims_sjz6_user
spring.datasource.password=B8H7aUmxczDKBTMKiSNwPgz4Y6HsmlNf

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect